version: '3.8'

services:
  web:
    build: .
    container_name: avatarium-django
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DEBUG=1
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: avatarium-db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: avatarium_db
      POSTGRES_USER: avatarium_user
      POSTGRES_PASSWORD: avatarium_pass
    ports:
      - "5432:5432"

volumes:
  postgres_data:
