services:
  web:
    build: .
    container_name: avatarium-django
    command: sh -c "python manage.py migrate && gunicorn avatarium.wsgi:application --bind 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - SECRET_KEY=${SECRET_KEY:-dev-insecure-change-me}
      - DEBUG=${DEBUG:-False}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-*}
      - DB_ENGINE=django.db.backends.postgresql
      - DB_NAME=avatarium_db
      - DB_USER=avatarium_user
      - DB_PASSWORD=avatarium_pass
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: avatarium-db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: avatarium_db
      POSTGRES_USER: avatarium_user
      POSTGRES_PASSWORD: avatarium_pass
    ports:
      - "5432:5432"

volumes:
  postgres_data:
