# Generated by Django 5.1.1 on 2024-10-04 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('cost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('reg_time', models.DateTimeField()),
                ('balance', models.IntegerField()),
                ('avatarka', models.ImageField(default='avatars/base_ava.svg', upload_to='avatars')),
                ('tasks', models.ManyToManyField(blank=True, to='game.task')),
            ],
        ),
    ]
