# Generated by Django 5.1.1 on 2024-10-05 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_quest_users_quests'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='top',
            field=models.BooleanField(default=False),
        ),
    ]
