# Generated by Django 5.1.1 on 2024-10-05 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_quest_top'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='quests',
        ),
        migrations.CreateModel(
            name='UserQuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.quest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.users')),
            ],
        ),
    ]
