# Generated by Django 5.1.1 on 2024-10-05 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_remove_users_quests_userquest'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='quests/logos/'),
        ),
    ]
