# Generated by Django 5.1.1 on 2024-10-07 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_quest_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='info_image',
            field=models.ImageField(blank=True, null=True, upload_to='quests/images/'),
        ),
    ]
