# Generated by Django 5.1.2 on 2024-10-10 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_taskcategory_task_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='user_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
