# Generated by Django 5.1.2 on 2024-10-11 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_task_user_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcategory',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
