# Generated by Django 5.1.2 on 2024-10-11 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_taskcategory_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='sub_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
