# Generated by Django 5.1.2 on 2024-10-14 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_task_image_alter_users_avatarka'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='top',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='UserTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.quest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.task')),
            ],
        ),
    ]
