# Generated by Django 5.1.1 on 2024-10-15 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_alter_usertask_task_alter_usertask_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='far',
            field=models.BooleanField(default=False),
        ),
    ]
