# Generated by Django 5.1.1 on 2024-10-15 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0016_task_far'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='tasks',
        ),
    ]
