# Generated by Django 5.1.1 on 2024-10-15 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0017_remove_users_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcategory',
            name='russian_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
