# Generated by Django 5.1.1 on 2024-10-15 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0018_taskcategory_russian_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskcategory',
            name='russian_name',
        ),
    ]
