# Generated by Django 5.1.2 on 2024-10-20 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0021_alter_useractivity_activity_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserActivity',
        ),
    ]
