# Generated by Django 5.1.2 on 2024-10-20 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0023_taskcomment_alter_task_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='user_comment',
        ),
        migrations.RemoveField(
            model_name='taskcommentimages',
            name='comment_image',
        ),
        migrations.AddField(
            model_name='taskcomment',
            name='task',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='game.task'),
        ),
        migrations.AddField(
            model_name='taskcommentimages',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tasks/comment_images/'),
        ),
        migrations.AlterField(
            model_name='taskcommentimages',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='game.taskcomment'),
        ),
    ]
