# Generated by Django 5.1.1 on 2024-10-21 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0024_remove_task_user_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcomment',
            name='user_comment',
            field=models.TextField(),
        ),
    ]
