# Generated by Django 5.1.2 on 2024-10-23 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0025_alter_taskcomment_user_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='quests/logos/'),
        ),
        migrations.AlterField(
            model_name='taskcategory',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='tasks/logos'),
        ),
    ]
