# Generated by Django 5.1.2 on 2024-10-23 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0026_alter_quest_logo_alter_taskcategory_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('promo_img', models.FileField(blank=True, null=True, upload_to='promo')),
            ],
        ),
        migrations.AlterField(
            model_name='userquest',
            name='quest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_quests_relations', to='game.quest'),
        ),
        migrations.AlterField(
            model_name='userquest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_quests', to='game.users'),
        ),
        migrations.AlterField(
            model_name='users',
            name='avatarka',
            field=models.ImageField(default='avatars/def_ava.png', upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='users',
            name='balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='users',
            name='reg_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='usertask',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tasks_relations', to='game.users'),
        ),
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.quest')),
                ('promo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.promo')),
            ],
        ),
        migrations.CreateModel(
            name='UserVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='game.users')),
            ],
        ),
    ]
