# Generated by Django 5.1.2 on 2024-10-25 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0027_promo_alter_userquest_quest_alter_userquest_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherUrls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_url', models.TextField(blank=True, null=True)),
                ('practice_url', models.TextField(blank=True, null=True)),
                ('cource_url', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VideoUrls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
