# Generated by Django 5.1.2 on 2024-10-26 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0028_otherurls_videourls'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherurls',
            name='cource_img',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='otherurls',
            name='post_img',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='otherurls',
            name='practice_img',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
