# Generated by Django 5.1.2 on 2024-10-27 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0029_otherurls_cource_img_otherurls_post_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uservisit',
            name='visit_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
