# Generated by Django 5.1.2 on 2024-10-27 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0031_alter_uservisit_visit_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='uservisit',
            name='visit_time',
            field=models.DateTimeField(),
        ),
    ]
