# Generated by Django 5.1.2 on 2024-10-27 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0032_users_streak_alter_uservisit_visit_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uservisit',
            name='visit_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
