# Generated by Django 5.1.2 on 2024-10-27 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0033_alter_uservisit_visit_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='week_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
