# Generated by Django 5.1.2 on 2024-10-27 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0035_rename_week_start_date_users_visit_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='visit_time',
            new_name='week_start_date',
        ),
    ]
