# Generated by Django 5.1.2 on 2024-11-05 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0037_users_email_users_phone_alter_uservisit_visit_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Мужчина'), ('female', 'Женщина'), ('attack_helicopter', 'Боевой вертолет')], default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='nickname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
