# Generated by Django 5.1.2 on 2024-11-14 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0038_users_date_of_birth_users_gender_users_nickname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presentation',
            name='quest',
        ),
    ]
