# Generated by Django 5.1.2 on 2024-11-16 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0040_questions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otherurls',
            options={'verbose_name': 'Дополнительные ссылки', 'verbose_name_plural': 'Дополнительные ссылки'},
        ),
        migrations.AlterModelOptions(
            name='presentation',
            options={'verbose_name': 'Слайдер', 'verbose_name_plural': 'Слайдер'},
        ),
        migrations.AlterModelOptions(
            name='promo',
            options={'verbose_name': 'Акция', 'verbose_name_plural': 'Акции'},
        ),
        migrations.AlterModelOptions(
            name='quest',
            options={'verbose_name': 'Квест', 'verbose_name_plural': 'Квесты'},
        ),
        migrations.AlterModelOptions(
            name='questions',
            options={'verbose_name': 'Вопрос и ответ', 'verbose_name_plural': 'Вопросы и ответы'},
        ),
        migrations.AlterModelOptions(
            name='taskcategory',
            options={'verbose_name': 'Категория задачи', 'verbose_name_plural': 'Категории задач'},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterModelOptions(
            name='videourls',
            options={'verbose_name': 'Ютуб видео', 'verbose_name_plural': 'Ютуб видео'},
        ),
        migrations.RemoveField(
            model_name='promo',
            name='description',
        ),
    ]
