# Generated by Django 5.1.2 on 2024-11-16 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0041_alter_otherurls_options_alter_presentation_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otherurls',
            name='cource_img',
        ),
        migrations.RemoveField(
            model_name='otherurls',
            name='cource_url',
        ),
    ]
