# Generated by Django 5.1.2 on 2024-11-20 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0042_remove_otherurls_cource_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='telegram_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
