# Generated by Django 5.1.2 on 2024-11-20 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0043_users_telegram_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='post_time',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='usertask',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
