# Generated by Django 5.1.4 on 2024-12-10 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0045_userweeklychallenge'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserChallengeDailyTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start_date', models.DateField()),
                ('task_number', models.IntegerField()),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_daily_tasks', to='game.users')),
            ],
            options={
                'unique_together': {('user', 'week_start_date', 'task_number')},
            },
        ),
    ]
