# Generated by Django 5.1.2 on 2024-12-11 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0045_remove_task_description_taskitem'),
        ('game', '0046_userchallengedailytask'),
    ]

    operations = [
    ]
