# Generated by Django 5.1.4 on 2024-12-15 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0046_userchallengedailytask'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchallengedailytask',
            name='date',
            field=models.DateField(default='2024-01-01'),
            preserve_default=False,
        ),
    ]
