# Generated by Django 5.1.2 on 2024-12-15 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0047_userchallengedailytask_date'),
        ('game', '0050_alter_task_title'),
    ]

    operations = [
    ]
