# Generated by Django 5.1.2 on 2024-12-15 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0051_merge_20241215_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskitem',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userweeklychallenge',
            name='challenge_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
