# Generated by Django 5.1.2 on 2024-12-19 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0053_alter_userchallengedailytask_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userweeklychallenge',
            name='week_start_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
