# Generated by Django 5.1.2 on 2024-12-23 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0055_userweeklychallenge_friday_cont_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userweeklychallenge',
            old_name='friday_cont',
            new_name='friday_count',
        ),
        migrations.RenameField(
            model_name='userweeklychallenge',
            old_name='monday_cont',
            new_name='monday_count',
        ),
        migrations.RenameField(
            model_name='userweeklychallenge',
            old_name='saturday_cont',
            new_name='saturday_count',
        ),
        migrations.RenameField(
            model_name='userweeklychallenge',
            old_name='sunday_cont',
            new_name='sunday_count',
        ),
        migrations.RenameField(
            model_name='userweeklychallenge',
            old_name='thursday_cont',
            new_name='thursday_count',
        ),
        migrations.RenameField(
            model_name='userweeklychallenge',
            old_name='tuesday_cont',
            new_name='tuesday_count',
        ),
    ]
