# Generated by Django 5.1.2 on 2024-12-23 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0056_rename_friday_cont_userweeklychallenge_friday_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userweeklychallenge',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userchallengedailytask',
            name='date',
            field=models.DateField(),
        ),
    ]
