# Generated by Django 5.1.2 on 2024-12-24 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0057_userweeklychallenge_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchallengedailytask',
            name='week_completed',
            field=models.BooleanField(default=False),
        ),
    ]
