# Generated by Django 5.1.2 on 2024-12-24 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0058_userchallengedailytask_week_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userchallengedailytask',
            name='week_completed',
        ),
    ]
