# Generated by Django 5.1.2 on 2025-01-03 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0059_remove_userchallengedailytask_week_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='promo',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
