# Generated by Django 5.1.2 on 2025-01-24 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0060_promo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='complete_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
