# Generated by Django 5.1.2 on 2025-01-24 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0061_task_complete_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='complete_time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
