# Generated by Django 5.1.2 on 2025-01-24 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0062_alter_task_complete_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservisit',
            name='day_index',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
