# Generated by Django 5.1.2 on 2025-01-25 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0063_uservisit_day_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presentation',
            name='promo',
        ),
        migrations.AddField(
            model_name='presentation',
            name='promos',
            field=models.ManyToManyField(blank=True, to='game.promo'),
        ),
    ]
