# Generated by Django 5.1.2 on 2025-01-25 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0064_remove_presentation_promo_presentation_promos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='presentation',
            options={'verbose_name': 'Слайдер', 'verbose_name_plural': 'Слайдеры'},
        ),
        migrations.AlterField(
            model_name='presentation',
            name='promos',
            field=models.ManyToManyField(blank=True, related_name='presentations', to='game.promo'),
        ),
    ]
