# Generated by Django 5.1.2 on 2025-01-25 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0065_alter_presentation_options_alter_presentation_promos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presentation',
            name='promos',
        ),
        migrations.AddField(
            model_name='presentation',
            name='promos',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='presentations', to='game.promo'),
        ),
    ]
