# Generated by Django 5.1.2 on 2025-01-25 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0066_remove_presentation_promos_presentation_promos'),
    ]

    operations = [
        migrations.AddField(
            model_name='promo',
            name='show_place',
            field=models.CharField(choices=[('library', 'Библиотека'), ('main', 'Главная')], default='library', max_length=50),
        ),
        migrations.DeleteModel(
            name='Presentation',
        ),
    ]
