# Generated by Django 5.1.2 on 2025-01-25 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0067_promo_show_place_delete_presentation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VideoUrls',
        ),
        migrations.AlterField(
            model_name='otherurls',
            name='post_img',
            field=models.FileField(blank=True, null=True, upload_to='library'),
        ),
        migrations.AlterField(
            model_name='otherurls',
            name='practice_img',
            field=models.FileField(blank=True, null=True, upload_to='library'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='show_place',
            field=models.CharField(choices=[('library', 'Библиотека'), ('main', 'Главная')], default='main', max_length=50),
        ),
    ]
