# Generated by Django 5.1.5 on 2025-02-03 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0069_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='counter',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
