# Generated by Django 5.1.5 on 2025-02-03 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0070_counter_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='counter',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
